"""
Regenerate flood_data_embedded.js from flood_timeseries_aggregated.json.

index.html loads this file via a classic <script> tag, so the dataset is
available immediately even under file:// (where fetch() is CORS-blocked).
Run this script whenever flood_timeseries.py rebuilds the JSON.
"""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "flood_timeseries_aggregated.json")
OUT = os.path.join(BASE, "flood_data_embedded.js")

with open(SRC, encoding="utf-8") as f:
    data = json.load(f)

# Compact single-line literal, safe inside a <script> block:
#   "</"            -> "<\/"   (escaped solidus, identical string value)
#   U+2028 / U+2029 -> escaped (invalid line terminators in older JS)
text = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
text = text.replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/embed_flood_data.py from flood_timeseries_aggregated.json\n")
    f.write("// Same NOAA NCEI + FEMA NRI dataset; do not edit by hand.\n")
    f.write("window.__FLOOD_DATA__ = ")
    f.write(text)
    f.write(";\n")

print("wrote", OUT, os.path.getsize(OUT), "bytes")
